export enum Role {
  ADMIN = 'ADMIN',
  DOCKER_ACCESS = 'DOCKER_ACCESS',
  COMPOSE_ACCESS = 'COMPOSE_ACCESS',
  PROXY_ACCESS = 'PROXY_ACCESS',
  WEBUPLOAD_ACCESS = 'WEBUPLOAD_ACCESS',
  TASK_ACCESS = 'TASK_ACCESS'
}
